@startuml
left to right direction

actor Student
actor admin

Student --> (createTest)
Student --> (checkTest)

admin --> (createQuestion)
admin --> (readQuestionsBySubjectAndEvaluation)
admin --> (updateQuestion)
admin --> (deleteQuestion)
admin --> (createQuestionsFromDaypo)

@enduml
